version: '3.9'

networks:
  app_network:
    driver: bridge
    external: true

services:
  database:
    image: mongo:6.0
    container_name: database_service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - app_network
    command: ["mongod", "--bind_ip", "0.0.0.0", "--auth"]
    restart: always

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - app_network
    restart: always

volumes:
  mongo_data: